spring:
  devtools:
    restart:
      enabled: false
  docker:
    compose:
      lifecycle-management: start_only
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 1000
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimension: 1536
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://pgvector:5432/mydatabase
    username: myuser
    password: secret

logging:
  level:
    org:
      apache:
        pdfbox:
          pdmodel:
            font:
              FileSystemFontProvider: ERROR